flowchart TD
    A(["Start"]) --> B["Execute Task"]
    B --> C{"Successful?"}
    C -->|Yes| D(["Save Progress to Storage"])
    C -->|No| E["Load Last Consistent Progress from Storage"]
    D --> F{"Successful?"}
    F -->|Yes| G(["Success"])
    F -->|No| H(["Failed"])
    E --> I{"Successful?"}
    I -->|Yes| J["Rollforward to Correct State Before the Event"]
    I -->|No| H
    J --> K{"Successful?"}
    K -->|Yes| B
    K -->|No| H