# .readthedocs.yaml
# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # Can also use "latest"
  ##
  # We need this in combination with sphinxcontrib-plantuml (python/pip
  # dependency) so PlantUML diagrams can be generated and embedded into
  # the output during build.
  #
  apt_packages:
    - plantuml

sphinx:
  configuration: conf.py
  # TODO: Fail on all warning to avoid broken references
  #fail_on_warning: true

# Build documentation in additional formats
formats:
  - pdf

python:
   install:
   - requirements: requirements.txt

